### ISSUE TITLE
Came close but Error 

### ISSUE THREAD

**Issue by dmijsMe71274** [johnsmith80/REALTEK-RTL8192FU#1]
Hello, it was nice of you "JohnSmith80" to help us & those having this kind of legacy wifi adapter. But the reason im writing this is i still didnt finish the installation, there was an error:

/home/linuxdrm/Downloads/RTL8192FU_RTL8725AU_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c: In function ‘isFileReadable’:
/home/linuxdrm/Downloads/RTL8192FU_RTL8725AU_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c:2223:11: error: implicit declaration of function ‘get_fs’; did you mean ‘get_sa’? [-Werror=implicit-function-declaration]
 2223 |   oldfs = get_fs();
      |           ^~~~~~
      |           get_sa
/home/linuxdrm/Downloads/RTL8192FU_RTL8725AU_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c:2223:11: error: incompatible types when assigning to type ‘mm_segment_t’ from type ‘int’
/home/linuxdrm/Downloads/RTL8192FU_RTL8725AU_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c:2224:3: error: implicit declaration of function ‘set_fs’; did you mean ‘sget_fc’? [-Werror=implicit-function-declaration]
 2224 |   set_fs(get_ds());
      |   ^~~~~~
      |   sget_fc
/home/linuxdrm/Downloads/RTL8192FU_RTL8725AU_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c:2224:10: error: implicit declaration of function ‘get_ds’; did you mean ‘get_da’? [-Werror=implicit-function-declaration]
 2224 |   set_fs(get_ds());
      |          ^~~~~~
      |          get_da
 /home/linuxdrm/Downloads/RTL8192FU_RTL8725AU_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c: In function ‘retriveFromFile’:
/home/linuxdrm/Downloads/RTL8192FU_RTL8725AU_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c:2261:12: error: incompatible types when assigning to type ‘mm_segment_t’ from type ‘int’
 2261 |    oldfs = get_fs();
      |            ^~~~~~
/home/linuxdrm/Downloads/RTL8192FU_RTL8725AU_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c: In function ‘storeToFile’:
/home/linuxdrm/Downloads/RTL8192FU_RTL8725AU_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.c:2296:12: error: incompatible types when assigning to type ‘mm_segment_t’ from type ‘int’
 2296 |    oldfs = get_fs();
      |            ^~~~~~
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-5.14.0-kali2-common/scripts/Makefile.build:276: /home/linuxdrm/Downloads/RTL8192FU_RTL8725AU_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/os_dep/osdep_service.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.14.0-kali2-common/Makefile:1882: /home/linuxdrm/Downloads/RTL8192FU_RTL8725AU_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02/driver/rtl8192FU_rtl8725AU_WiFi_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02] Error 2
make[1]: *** [/usr/src/linux-headers-5.14.0-kali2-common/Makefile:232: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.14.0-kali2-amd64'
make: *** [Makefile:2327: modules] Error 2
##################################################
Compile make driver error: 2
Please check error Mesg
##################################################
                                                                                                     
┌──(linuxdrm㉿kali)-[~/Downloads/RTL8192FU_RTL8725AU_linux_v5.8.6.2_35538.20191028_COEX20190910-0d02]
└─$ 

- i used both instruction or ways you gave in installing. the 2nd method came closest to achieving it and this is the error that came out. Basically it didnt finish. 
- Now im one of the people who now know that installing and using this kind of legacy wifi adapter is a pain, plus the fact that im trying or testing it in kali-linux (driver + kali = pain) haha... im a student in pentesting.

**Comment by johnvexcoder** [comment]
Hello, Thank you for letting us know this issue, We fixed the driver and Its supported the kernel 5.16.0 now.
